name: Trigger Jenkins Staging

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  trigger-jenkins:
    if: github.event.pull_request.merged == true &&
      github.event.pull_request.head.ref != 'main'

    runs-on: ubuntu-latest

    steps:
      - name: Trigger Jenkins
        run: |
          curl -X POST \
            -u "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }}" \
            ${{ secrets.JENKINS_URL }}/job/gold-gym-be-v2-staging/build
